helsingborg-stad/Modularity

source/acf-json/group_56c47016ea9d5.json

The default value works better as a placeholder.

Move default value to placeholder

---

source/php/Display.php

Classnames are suddenly `modularity-modularity-mod-contacts` in latest release. This bug was introduced in 1bec9e16.

Fix double "module-" prefix in class-names

---

source/php/Module/WpWidget/WpWidget.php

This got a bit more complicated than I anticipated. The usecase I have is that the default RSS widget has a limit of 20 items which I need to increase. You could argue that I should open an issue to Wordpress Core...
Instead I duplicated the default widget into our own plugin. These filters makes it possible for me to replace the default rss widget with the custom widget.
The new filters are: 
`'Modularity/Module/WidgetIndexList`
`'Modularity/Module/WidgetSettings'`
I introduced a getter for WidgetIndexList since having it declared in the constructor seemed to be to happening before calls to `add_filter()`, thus too early.
This is how I use the filter:
```php
add_filter('Modularity/Module/WidgetIndexList', function($list) {
unset($list['WP_Widget_RSS']);
$list['Hoor_WP_Widget_RSS'] = …
```

Add filters to be able to add or alter widgets

---

source/php/Module/Posts/Posts.php

See https://github.com/helsingborg-stad/Modularity/issues/15 and https://github.com/helsingborg-stad/Modularity/pull/16 for background on this.
I also change the logic around _meta_key_ check. This now checks that it is a prefix, not just part of the string. I think that is more correct.
I have not tested this extensively (for example with NULL values) but it works for the date sort used for events on hoor.se

Fix sort by meta

---

templates/editor/modularity-enabled-modules.php

Check if module array has property set before using it.
Cleaning up messy row to multiple.

Avoid error log message in wp-admin

---

source/php/Display.php

Seems like you are missing to grab the post_content as subject for replace.
This causes render error when using the_post in WP Rest API

Variable missing in context

---

source/php/Helper/Acf.php

Checking if the classes 'acf_pro' or 'ACF' are loaded instead of using
'is_plugin_active'. This is more reliable since the 'is_plugin_active'
function for instance won't notice 'must-use' plugins.

Change how Modularity checks for ACF

---

source/php/Module/InheritPost/views/inheritposts.blade.php
source/php/Module/Posts/views/expandable-list.blade.php
source/php/Module/Posts/views/grid.blade.php
source/php/Module/Posts/views/index.blade.php
source/php/Module/Posts/views/items.blade.php
source/php/Module/Posts/views/list.blade.php
source/php/Module/Posts/views/news.blade.php

Post title filters in WordPress change certain characters to HTML-encoded variants. These were sometimes also escaped by Blade, resulting in the HTML-encoded variants being visible to end users.
The post title filters do not escape HTML tags from the title. While this could cause issues, the HTML-encoded characters makes it so that titles cannot be escaped without first disabling some of the built-in
post title filters.
Post titles are usually not escaped in Modularity, so this commit just makes that the case in all other places as well.

Fix double escaping of post titles

---

source/php/Module/Posts/views/circular.blade.php

Forgot to save a file yesterday!
See #46 for more details.

Fix another double escaping of post titles

---

source/php/Display.php

New method getModuleDirectory()
Getting correct module directory name by checking directories vs post type

Fix for camelCase Directories

---

source/php/BlockManager.php
source/php/Module.php
source/php/ModuleManager.php

Implement modules as blocks
- Add a new class that handles the registrering of modules as blocks
- Filter out all of the native blocks except the classic editor
- Add a new block category called Modules
- Add a location rule to all field groups that belongs to the a module, to allow them to be shown on corresponding block type
- Check if module is set as isBlockCompatible before registering

3.0/feature/module blocks

---

source/php/Search.php

Bail module search filter so it runs only on search queries where post type is set to "any".
Because when it runs on other archives it fucks up the search and also breaks pagination.

bail if post type query var is not set to Any

---

modularity.php
source/php/AcfFields/json/mod-contacts.json
source/php/AcfFields/json/mod-table-block.json
source/php/AcfFields/php/mod-contacts.php
source/php/AcfFields/php/mod-table-block.php
source/php/BlockManager.php

Add a new method that validates required fields.
Does not work on nested fields and is not intended to do that.
This is but a temporary solution until the ACF-team release
a solution.

Temporary validation for required fields in blocks

---

source/php/BlockManager.php

Made title field negative in menu order to always end up in top.

CU-1f95zd0 fix: make block title field earliest in order

---

source/php/AcfFields/json/mod-script.json
source/php/AcfFields/php/mod-script.php
source/php/Module/Script/Script.php
source/php/Module/Script/views/script.blade.php

Added support for a placeholder image in contexts where script elements cannot be rendered.
Actual placeholder is fetched from ACF and passes through Municipio hook on wp_get_attachment_src for automatic scaling (referenced by @sebastianthulin).
Implements in templates with @print media query through styleguide utility classes.

Added support for Script module placeholder image

---

source/php/Module/Script/Script.php
source/php/Module/Script/views/nothing.blade.php

Fixed.
Also when it started working the scripts ran in admin, so fixed that part too.
Also som blade stuff fixed.
It's kinda strange in my opinion that there are display options on how the scripts should be wrapped and so on (leading to that they were executed in preview). It's probably not optimal now, with the script code displayed in e.g. the card component (if chosen). But it looks OK and functions. This could perhaps be the object for future discussions.

Scripts didn't work in Guteberg + other fixes

---

source/php/AcfFields/json/mod-posts-taxonomydisplay.json
source/php/AcfFields/php/mod-posts-taxonomydisplay.php
source/php/Module/Posts/Posts.php

Display taxonomies wasn't saved when using Gutenberg.
Added json/php files for the ACF:s in question

Fixed Display Taxonomies in Gutenberg

---

source/php/Display.php
source/php/Module/Script/Script.php
source/php/Options/General.php

Fixes undefined values and other stuff that trigger PHP errors. 
Fixes: 
- global $post can be null on 404 pages (Display.php)
- wrap nested ternary with parentheses (Module\Script\Script.php)
- move get_field checks within the hooks (Options\General.php)

3.0/fix/php errors

---

source/php/Editor.php

Every time this function is called it grabs data for all modules and posts, and it's requested for all modules.
As we already get all the data we want the first time, and the $postId doesn't change in the same instance as far as i know. We can gain a significant speedboost during loading by doing caching it. (The more modules used on the post the higher the gain).
remove the unused $available variable.

statically cache "Editor\getPostModules" results.

---

source/php/BlockManager.php

Block type broken due to sub block type core/list-item not registered in allowed block types.

Block core/list broken

---

source/php/Module/Modal/Modal.php

Since values can be empty, the variable will still be defined leading to errors.

Fix: Empty values in modal module

---

source/php/App.php
source/php/Module/Divider/Divider.php
source/php/Upgrade.php

Added functions:
v_1: Handling divider fields as test for first upgrade
Normal modules:
- migrateAcfFieldsValueToNewFields
- migrateModuleFields
Blocks:
- migrateBlockFieldsValueToNewFields
- migrateBlockFields
- getPagesFromBlockName

Feat: Upgrade init

---

source/php/Module/Hero/views/image.blade.php

Gets passed in context param instead.

fix: removes unrecongnized sidebar context in hero module.

---

source/php/Module/Posts/Helper/GetPosts.php
source/php/Module/Posts/TemplateController/ListTemplate.php

This pull request includes changes to improve the handling of post permalinks when fetching posts from multiple sites. The most important changes are in the `GetPosts.php` and `ListTemplate.php` files.
Improvements to permalink handling:
* [`source/php/Module/Posts/Helper/GetPosts.php`](diffhunk://#diff-38bb160590c235cf5e69c693a8492cebeb9148eb34398558504db10765d36e5aL58-R64): Added `originalPermalink` to each post fetched from other sites to ensure the permalink is correctly stored.
* [`source/php/Module/Posts/TemplateController/ListTemplate.php`](diffhunk://#diff-3e77677d2039d4609b13d8eda845eabb1cf4aaaa579d1bd664635ec516fdf86bL46-R46): Modified the permalink assignment to use `originalPermalink` if available, ensuring the correct permalink is used for posts.

fix(mod-posts): incorrect permalink to other sites posts

---

source/php/Module/Posts/Posts.php

This pull request includes a modification to the `loadNetworkSourcesField` function in the `Posts.php` file to improve the efficiency of retrieving site information.
Improvements to efficiency:
* [`source/php/Module/Posts/Posts.php`](diffhunk://#diff-a319adf96c3b45b0665ad99c309d7b0b73484b508a634c21889d97a3f724c26bL96-R96): Updated the `get_sites` function call to include the `['number' => 0]` parameter, ensuring all sites are retrieved without a limit. This change optimizes the process of fetching site data.

fix(posts): remove limit on site query (default was 100)

---

source/php/Module/Posts/Helper/GetPosts.php
source/php/Module/Posts/Helper/GetPostsTest.php

This pull request introduces enhancements to the `GetPosts` class in the `source/php/Module/Posts/Helper` directory, including dependency injection improvements and the addition of unit tests. The most important changes are the inclusion of new service contracts, the refactoring of the `getCurrentPostID` method, and the creation of a new test class for `GetPosts`.
* [`source/php/Module/Posts/Helper/GetPosts.php`](diffhunk://#diff-38bb160590c235cf5e69c693a8492cebeb9148eb34398558504db10765d36e5aR8-R17): Added `GetTheID` and `IsArchive` contracts to the constructor for better encapsulation and service usage.
* [`source/php/Module/Posts/Helper/GetPosts.php`](diffhunk://#diff-38bb160590c235cf5e69c693a8492cebeb9148eb34398558504db10765d36e5aL246-R258): Refactored the `getCurrentPostID` method to …

refactor(mod-posts): avoid missing one post when used as archive module

---

source/php/Module/Posts/Helper/GetPosts.php
source/php/Module/Posts/Helper/GetPostsTest.php

This pull request introduces a new feature to sort posts by various criteria and includes corresponding unit tests to ensure the functionality works as expected. The key changes involve adding a new method to sort posts and updating the test suite to cover the new sorting functionality.
* Added `sortPosts` method to `GetPosts` class to sort posts by date, title, modified date, menu order, or randomly.
* Updated `getPostsFromSelectedSites` method to use the new `sortPosts` method for sorting posts before limiting the number of posts.
* Added multiple test cases in `GetPostsTest` to verify the `sortPosts` method sorts posts correctly by different criteria and orders.
* Included utility method `getWpPostMock` in `GetPostsTest` to create mock `WP_Post` objects for testing.
* Imported …

feat(GetPosts): add sorting functionality for posts by various criteria

---

source/php/AcfFields/json/mod-posts-displau.json
source/php/AcfFields/php/mod-posts-displau.php
source/php/Module/Posts/TemplateController/ListTemplate.php
source/php/Module/Posts/views/list.blade.php

This pull request introduces a new feature to use term icons as icons in post lists and includes several improvements and refactorings in the `mod-posts-displau` module. The most important changes include adding a new field for the term icon feature, updating default values to use translations, and refactoring code for better readability and consistency.
* Added a new field `use_term_icon_as_icon_in_list` to enable using term icons as icons in the post list. This field is a true/false type and is conditionally displayed based on the value of another field. (`source/php/AcfFields/json/mod-posts-displau.json`, `source/php/AcfFields/php/mod-posts-displau.php`) [[1]](diffhunk://#diff-5ff23a5049c7632ad5a52728c14e63be0972ccbb2beb1bb2c36259e44e575958R37-R65) …

feat: add option to use term icon in posts list and update related logic

---

source/php/Upgrade.php
source/php/Upgrade/Migrators/Module/AcfModuleRepeaterFieldsMigrator.php
source/php/Upgrade/Version/V8.php

This pull request introduces a new upgrade version for the database schema and includes changes to handle the migration of old post modules. The most important changes involve updating the database version and adding a new class to manage the migration process.
Database version update:
* [`source/php/Upgrade.php`](diffhunk://#diff-126f7336ececf01562d4dc2fd784a150414750cccc75c64d722c8944f039d0e1L14-R14): Updated the `dbVersion` from 7 to 8.
Migration process for old post modules:
* [`source/php/Upgrade/Version/V8.php`](diffhunk://#diff-1f1fb32a4d9a2d31da4bd10c33a08fcaef42ae247d5dcc4ac5c1a47a6a909c19R1-R93): Added a new class `V8` that implements the `versionInterface` to handle the migration of old post modules to the new structure. This class includes methods to upgrade modules and …

feat: upgrade for modules missing content

---

source/php/Module/Slider/Slider.php
source/php/Module/Slider/Slider.test.php

This pull request introduces a new method to check if a slide has a link and adds corresponding unit tests to ensure the method works correctly. The main changes include modifying the `getLinkData` method to use the new `slideHasLink` method and adding a new test class for the `Slider` module.
* [`source/php/Module/Slider/Slider.php`](diffhunk://#diff-27d39ddc53c1fa6f01d6a17ba7268c0c4d778f1694a1bc25a71375c483f22156L205-R206): Added a new method `slideHasLink` to check if a slide has a valid link and updated the `getLinkData` method to use this new method. [[1]](diffhunk://#diff-27d39ddc53c1fa6f01d6a17ba7268c0c4d778f1694a1bc25a71375c483f22156L205-R206) [[2]](diffhunk://#diff-27d39ddc53c1fa6f01d6a17ba7268c0c4d778f1694a1bc25a71375c483f22156R232-R249)
* …

feat: add slideHasLink method and corresponding tests for link validation

---

source/php/Module/Posts/TemplateController/AbstractController.php

This pull request includes a small change to the `source/php/Module/Posts/TemplateController/AbstractController.php` file. The change ensures that the `preparePosts` function handles a null value for the `$posts` parameter by providing a default empty array.
* [`source/php/Module/Posts/TemplateController/AbstractController.php`](diffhunk://#diff-980419417ddbc5e348ccc543ee9c4cdf01e82b3e271f1b3c95ec5c3571dae4e8L99-R99): Updated the `preparePosts` function to use the null coalescing operator for the `$posts` parameter to ensure it defaults to an empty array if null.

fix: handle null posts array in AbstractController

---

source/php/Upgrade.php

* [`source/php/Upgrade.php`](diffhunk://#diff-126f7336ececf01562d4dc2fd784a150414750cccc75c64d722c8944f039d0e1R25-R28): Added a check to ensure that only super admins can proceed with the `addAdminNotice` function by returning early if the user is not a super admin.

fix: added a check to ensure that only super admins will see upgrade info

---

source/php/AcfFields/json/mod-manual-input.json
source/php/AcfFields/php/mod-manual-input.php
source/php/Module/ManualInput/ManualInput.php
source/php/Module/ManualInput/views/accordion.blade.php

This pull request includes changes to the `source/php/Module/ManualInput` module to remove the "Title as heading" feature and update the related logic. The most important changes include removing the field definition for "Title as heading" and updating the conditional logic in the `accordion.blade.php` view file.
Removal of "Title as heading" feature:
* [`source/php/AcfFields/json/mod-manual-input.json`](diffhunk://#diff-0b424789c17273fa038000a7d2acdcf33d3ce674d8bf35aa8f5fe0adc362124bL150-L177): Removed the "Title as heading" field definition.
* [`source/php/AcfFields/php/mod-manual-input.php`](diffhunk://#diff-6c60b6a8d7a5aa3e94b9ce98b64215191c9a0faedbbeeec7ad14ee5ffeb37b64L155-L182): Removed the "Title as heading" field configuration.
* …

fix: remove options that allow user to create ugly UI.

---

source/php/Display.php
source/php/Helper/Cache.php

This pull request introduces enhancements to the caching mechanism by adding support for a customizable cache group, improving flexibility in cache key generation. The changes primarily affect the `Cache` class and its usage in the `Display` module.
* **Support for customizable cache groups in `Cache` class**:
- Added a new `$cacheGroup` parameter to the `Cache` class constructor, allowing developers to specify a custom cache group. If not provided, it defaults to an empty string. (`source/php/Helper/Cache.php`, [source/php/Helper/Cache.phpL21-R30](diffhunk://#diff-4dbe8bb106a6d155b59d7460f1c9ac7fa4815ad1a43d44971f8e3fa46a8933e0L21-R30))
- Updated the cache hash generation logic to include the `$cacheGroup` value, ensuring more granular cache key differentiation. …

fix: create unique cache groups on get params.

---

source/php/BlockManager.php

When modularity modules are used as blocks in Gutenberg, provide a wrapper div with proper class equal to the one used in the regular module locations.

feat: modularity module wrapper when Gutenberg block
