source/php/Search.php
This implements search on module description.
https://github.com/helsingborg-stad/Modularity/issues/14#issuecomment-305423977 is relevant - I have only tested this with `moduleSearch()` being disabled.
=> Search module description

gulpfile.js
=> Add build task to Gulp

languages/modularity-sv_SE.po
(Forgot to add the actual translation in #37...)
=> Add missing PO file

source/php/Editor.php
This nearly cuts the number of sql-queries in half.
=> Reduced amount of SQL calls

source/php/Editor.php
=> Remove var_dump() comment

source/php/Display.php, source/php/Module/Contacts/views/cards.blade.php, source/php/Module/Contacts/views/contacts.blade.php, source/php/Module/Contacts/views/list.blade.php, source/php/Module/InheritPost/views/inheritposts.blade.php, source/php/Module/Text/views/article.blade.php, source/php/Module/Text/views/box.blade.php
- add filter to allow nested modules which are not parent module
=> Allow Nested shortcodes

source/php/Module/Gallery/Gallery.php, source/php/Module/Gallery/views/gallery.blade.php, source/php/Module/Text/views/article.blade.php, source/php/Module/Text/views/box-v3.blade.php.example, source/php/Module/Text/views/box.blade.php
Gallery module: Added gallery component from the component library
Moved logic (foreach loop) from view to controller.
Text module:Added typography component from the component library
=> Gallery and text module

source/php/Display.php
- add return of value instead of return of bool
=> Rendering of Modules

source/php/Module/InlayList/InlayList.php, source/php/Module/InlayList/views/inlaylist.blade.php
- add component
- add data handling for component
=> Inlay list

source/php/Module/Index/views/index.blade.php
- add use of components in index module
=> Index module

source/php/Module/Slider/views/partials/featured.blade.php, source/php/Module/Slider/views/partials/image.blade.php, source/php/Module/Slider/views/partials/textblock.blade.php, source/php/Module/Slider/views/partials/video.blade.php, source/php/Module/Slider/views/slider.blade.php
=> Slider - HTML to Blade

source/php/Module/Notice/Notice.php, source/php/Module/Notice/views/notice.blade.php
- add function in controller to support blade comp
- add blade component
=> Notice - HTML to Blade

source/php/Module/Contacts/Contacts.php, source/php/Module/Contacts/views/cards.blade.php, source/php/Module/Contacts/views/components/adress.blade.php, source/php/Module/Contacts/views/components/link.blade.php, source/php/Module/Contacts/views/components/opening_hours.blade.php, source/php/Module/Contacts/views/components/visiting.blade.php, source/php/Module/Contacts/views/list.blade.php
Replaced html with blade components
=> 3.0/feature/contacts module

source/php/Module/Table/Table.php, source/php/Module/Table/views/table.blade.php
- add replace html with blade
- add function in controller to work with component
=> Table Module - HTML to Blade

source/php/Module/Slider/views/partials/video.blade.php
Dependent on:
https://github.com/helsingborg-stad/blade-component-library/pull/131
https://github.com/helsingborg-stad/styleguide/pull/294
=> Added video background to slider

source/php/Module/Contacts/Contacts.php, source/php/Module/Contacts/views/cards.blade.php, source/php/Module/Contacts/views/components/adress.blade.php, source/php/Module/Contacts/views/components/email.blade.php, source/php/Module/Contacts/views/components/link.blade.php, source/php/Module/Contacts/views/components/opening_hours.blade.php, source/php/Module/Contacts/views/components/phone.blade.php, source/php/Module/Contacts/views/components/social_media.blade.php, source/php/Module/Contacts/views/components/visiting.blade.php, source/php/Module/Contacts/views/list.blade.php, source/php/Module/Contacts/views/partials/information.blade.php, source/php/Module/Contacts/views/partials/list_info.blade.php
- add function that allows you to check if a field is to be hidden
- parsing of data depending of view
=> Contacts v2 Controller

source/php/Module/FilesList/FilesList.php, source/php/Module/FilesList/views/fileslist.blade.php
Changed to collection and ignore old column functionality.
=> CU-9wuttg Changed to collection and some refactoring

source/php/Module/Contacts/views/components/title.blade.php, source/php/Module/Contacts/views/partials/information.blade.php
Added new partial title to contact card view.
Shows when any of administration_unit, full_name, work_title is present.
=> 3.0/fix/contact card without name cu 9wqv1b

source/php/Module/Posts/Posts.php
Post module: Activated fallback view from news-item to index.
=> Replaced views - replaced with index

source/php/Module/Contacts/views/components/email.blade.php
Added typography component with class for emails
=> contact module - E-mail with word-break

source/php/Module/Posts/views/expandable-list.blade.php
Removed old header. The Accordion component handle all headers.
=> Removed old header

source/php/AcfFields/json/mod-contacts.json, source/php/AcfFields/php/mod-contacts.php
Removed back end acf field Display settings on Contacts module.
=> Removed Display settings

composer.lock, package-lock.json, source/php/Module/Posts/TemplateController/ExpandableListTemplate.php, source/php/Module/Posts/views/expandable-list.blade.php
=> Expandable list - Hide column titles

source/php/Module/Posts/TemplateController/ExpandableListTemplate.php
Fixed column values for manuel selected post and manual input.
=> Module: Expandable list - Column values

source/php/Display.php, source/php/Module/Contacts/Contacts.php, source/php/Module/Index/Index.php, source/php/Module/Posts/TemplateController/ExpandableListTemplate.php, source/php/Module/Slider/Slider.php, source/php/Module/Table/Table.php
Removed Warnings in modules:
Slider, Expandable list, Index, Table, Contacts2
Also Fixed the check for Missing properties in Display.
=> 3.0/feature/errors warning notices

source/php/Module/Contacts/views/components/other.blade.php, source/php/Module/Contacts/views/list.blade.php, source/php/Module/Contacts/views/partials/information.blade.php, source/php/Module/Contacts/views/partials/list_info.blade.php
Added blade partial for showing content ("other information") when card and Horizontal card is selected.
=> Added collection item for content

source/php/Module/Map/views/map.blade.php, source/sass/partials/_modules.scss
=>  - add icon before header

source/php/BlockManager.php
=> Calculate width on columns and render a div grid

source/php/AcfFields/json/mod-slider.json, source/php/AcfFields/php/mod-slider.php
Removes some options not nedded anymore, these are moved to customizer settings in muncipio.
=> Remove options that isen’t needed anymore.

source/php/AcfFields/json/mod-contacts.json, source/php/AcfFields/php/mod-contacts.php
Some additional ACF settings seems to have been generated on the update of the files. Not sure if that's a problem or not.
=> Removal of  backend ACF fields for Contacts module

source/php/Module/Iframe/views/iframe.blade.php
=> Changed iframe module attributes

source/php/Module/Video/assets/video.js, source/php/Module/Video/views/video.blade.php
Fixed: Embeded videos no workey in Gutenberg.
Also fixed: Poster Image didn't work either
=> Video bugs in Gutenberg

composer.json, composer.lock, modularity.php, source/php/AcfFields/json/mod-posts-taxonomydisplay.json, source/php/AcfFields/php/mod-posts-taxonomydisplay.php, source/php/Module/Posts/Posts.php, source/php/Plugins.php
This should do the trick with displaying the taxonomies,
ACF extended required and included with other Plugins
Also added the php/json files for sync
=> 3.0/bug/posts tax gutenberg 2

source/php/Module/Posts/assets/mod-posts-taxonomy.js
Taxonomy selector now working in Gutenberg.
=> Fixed Gutenberg problems with taxonomy selector

source/php/Module/Script/Script.php
Class attr was false due to value beign "0".
=> Small empty class fix

source/php/Module/Posts/TemplateController/SliderTemplate.php
Waiting for purpose templates to be implemented
=> Changed from purpose templates to post type

source/php/AcfFields/json/mod-curator.json, source/php/AcfFields/php/mod-curator.php, source/php/Helper/Block.php, source/php/Module/Curator/Curator.php, source/php/Module/Curator/views/partials/card.blade.php
- Only display ratio field on block layout
- Removed gutter and ratio settings for card layout 
- Added helper class for fetching field data on blocks 
- Apply block settings if not a module 
- Respect block and/or module settings for columns on card layout
=> feature/Card vy funkar inte med ajax inladdning eller modal CU 865bx8knq

source/php/Module/Posts/views/collection.blade.php, source/php/Module/Posts/views/partials/slider/grid.blade.php, source/php/Module/Posts/views/partials/slider/segment.blade.php, source/php/Module/Posts/views/segment.blade.php
Hides term icon based on kirki field
=> init hide term icon

source/php/Module/Posts/Posts.php, source/php/Module/Posts/TemplateController/AbstractController.php, source/php/Module/Posts/TemplateController/SegmentTemplate.php, source/php/Module/Posts/views/segment.blade.php
- Removed emblem fallback on featured image
- Handle emblem fallback on segment layout
=> feature/Bara vissa poster fr c card  svg background nr emblem visas som utvald bild cards CU 865c44xv1

source/php/Module/Curator/Curator.php, source/php/Module/Curator/views/partials/block.blade.php
- Respect gutter and ratio setting
- Renamed for clarity
- Added comment as hidden slot data (to prevent :after on empty body)
=> feature/BUGG   Social media Curator Kvadratiska bilder utan mellanrum CU 865c4kfap

.github/workflows/test-php.yml, .gitignore, bin/install-wp-tests.sh, build.php, composer.json, composer.lock, phpunit.xml.dist, source/js/editor/module.js, source/php/Options.Test.php, source/php/Options.php, source/php/Options/General.php, templates/options/modularity-options.php, tests/bootstrap.php
* Prevent saving modules if $_POST variable indicating that load is not done is present.
* Disable save-button until get_modules request is done.
=> Prevent save modules until load complete

source/php/Module/Text/Text.php, source/php/Module/Text/views/box.blade.php
Content not showing in gutenberg due to different key name. ID was missing from gutenberg causing error notices.
=> Fix: Text module gutenberg bugs

source/js/modularity.js
error thrown in administration interface
due to  not being (and should not be) available.
=> fix: catch error from ensureWPApiSettings

source/sass/partials/_editor.scss
Using material icons library instead
=> fix: modularity icons

source/php/App.php
Resolved in a similar manner here. Must be tested. https://github.com/Automattic/woocommerce-payments/pull/7484
=> fix: resolve that wp api settings is missing

source/php/AcfFields/json/mod-manual-input.json, source/php/AcfFields/php/mod-manual-input.php, source/php/Module/ManualInput/ManualInput.php, source/php/Module/ManualInput/views/appearances/card.blade.php
* Title above image
* Background color for cards
* Disable layout shift during viewport resize
=> feat: new manual input card settings
